// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            7
// Async Callback (empty):               1
// Total number of exported functions:   9

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    contract
    (
        init => init
        createTrip => create_trip
        buyTicket => buy_ticket
        issueNft => issue_nft
        getTokenId => get_token_id
        getTokenData => get_token_data
        tokenId => token_id
        trips => trips
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
