// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            5
// Async Callback:                       1
// Total number of exported functions:   7

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    contract
    (
        init => init
        createTrip => create_trip
        buyTicket => buy_ticket
        issueToken => issue_token
        nftTokenId => nft_token_id
        trips => trips
    )
}

multiversx_sc_wasm_adapter::async_callback! { contract }
